module.exports = {
  PO_DOCUMENT_TYPES: {
    PO_APPROVED: "PO_APPROVED",
    SUPPLIER_QUOTATION: "SUPPLIER_QUOTATION",
    PO_RELEASED: "PO_RELEASED",
  },

  // ✅ REQUIRED FOR STAGE-2 (APPROVAL)
  REQUIRED_APPROVAL_DOCS: [
    "PO_APPROVED",
    "SUPPLIER_QUOTATION",
  ],

  // ✅ REQUIRED FOR STAGE-3 (RELEASE)
  REQUIRED_RELEASE_DOCS: [
    "PO_RELEASED",
  ],
};
